### ISSUE TITLE
JSON serializable problem

### ISSUE THREAD

**Issue by zhiyue** [Rochester-NRT/RocAlphaGo#113]
python -m unittest discover

```
root@nova-06dfe62e-7394-4a94-96b1-28adf12cde98:/home/opuser/workspace/RocAlphaGo# python -m unittest discover
Using Theano backend.
GTP engine ready
=1 gtp (python library)

=2

=3

=4 PASS

=5 PASS

=99

.......................WARNING: rollout reached move limit
.WARNING: rollout reached move limit
WARNING: rollout reached move limit
..Epoch 1/1
205/205 [==============================] - 3s - loss: 0.0191
.Epoch 1/1
944/960 [============================>.] - ETA: 0s - loss: 5.8889 - acc: 0.0011E.............
======================================================================
ERROR: testTrain (tests.test_supervised_policy_trainer.TestSupervisedPolicyTrainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/opuser/workspace/RocAlphaGo/tests/test_supervised_policy_trainer.py", line 12, in testTrain
    run_training(args)
  File "/home/opuser/workspace/RocAlphaGo/AlphaGo/training/supervised_policy_trainer.py", line 218, in run_training
    nb_val_samples=n_val_data)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 651, in fit_generator
    max_q_size=max_q_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1424, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 39, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/opuser/workspace/RocAlphaGo/AlphaGo/training/supervised_policy_trainer.py", line 70, in on_epoch_end
    json.dump(self.metadata, f)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 0.0 is not JSON serializable

```

**Comment by wrongu** [comment]
Strange - haven't seen that before. Can you double check that your `json` and `keras` libraries are up to date (or that they match the `requirements.txt` file)?

**Comment by zhiyue** [comment]
@wrongu yes,  I use the command `pip install -r requirement.txt` before the test.,I guess the problem is the `json`.  When I debug, I found the logs variable to return to the four data types.`numpy.float64``numpy.float64``numpy.float32``numpy.float32`
`numpy.float64` can be sequenced,however `numpy.float32` is not.
The strange thing is that I do not have this problem on other machines.According to the error message.
The logs variable returns the string type.
It makes me confused.
