### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by oriskunk** [Rochester-NRT/RocAlphaGo#172]
train_rl.py
================================================================================
from AlphaGo.training.reinforcement_policy_trainer import run_training
from AlphaGo.models.policy import CNNPolicy

model_json = './model/48plane_policy_192.json'
initial_weights = './model/48plane_policy_192/weights.00000.hdf5'
out_directory = './model/working_rl'

args = [model_json, initial_weights, out_directory, '--verbose', '--game-batch', '10']

def _run_training():
    run_training(args)

if __name__ == '__main__':
    _run_training()

Traceback
================================================================================

Traceback (most recent call last):
  File "train_rl.py", line 14, in <module>
    _run_training()
  File "train_rl.py", line 11, in _run_training
    run_training(args)
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/training/reinforcement_policy_trainer.py", line 306, in run_training
    win_ratio = run_n_games(optimizer, player, opponent, args.game_batch)
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/training/reinforcement_policy_trainer.py", line 158, in run_n_games
    moves = current.get_moves(idxs_to_unfinished_states.values())
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/ai.py", line 136, in get_moves
    all_moves_distributions = self.policy.batch_eval_state(states, sensible_move_lists)
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/models/policy.py", line 44, in batch_eval_state
    nn_input = np.concatenate([self.preprocessor.state_to_tensor(s) for s in states], axis=0)
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/preprocessing/preprocessing.py", line 280, in state_to_tensor
    feat_tensors = [proc(state) for proc in self.processors]
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/preprocessing/preprocessing.py", line 170, in get_ladder_capture
    feature[0, x, y] = state.is_ladder_capture((x,y))
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 379, in is_ladder_capture
    for (escape_x, escape_y) in possible_escapes):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 379, in <genexpr>
    for (escape_x, escape_y) in possible_escapes):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 437, in is_ladder_escape
    for possible_capture in tmp.liberty_sets[prey_x][prey_y]):  
 File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 437, in <genexpr>
    for possible_capture in tmp.liberty_sets[prey_x][prey_y]):
  ...
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 379, in is_ladder_capture
    for (escape_x, escape_y) in possible_escapes):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 379, in <genexpr>
    for (escape_x, escape_y) in possible_escapes):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 437, in is_ladder_escape
    for possible_capture in tmp.liberty_sets[prey_x][prey_y]):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 437, in <genexpr>
    for possible_capture in tmp.liberty_sets[prey_x][prey_y]):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 379, in is_ladder_capture
    for (escape_x, escape_y) in possible_escapes):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 379, in <genexpr>
    for (escape_x, escape_y) in possible_escapes):
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 422, in is_ladder_escape
    tmp = self.copy()
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 189, in copy
    other = GameState(self.size, self.komi)
  File "/media/nhnent/H1/users/jhpark/RocAlphaGo/AlphaGo/go.py", line 61, in __init__
    WHITE: rng.randint(np.iinfo(np.uint64).max, size=(size, size), dtype='uint64'),
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/getlimits.py", line 247, in __init__
    self.dtype = numeric.dtype(int_type)
RuntimeError: maximum recursion depth exceeded

**Comment by wrongu** [comment]
Looks like we do need a hard maximum recursion depth on ladders
@thouis

**Comment by thouis** [comment]
This is surprising.  Each call should result in at least one move being made, so I would have expected it to reach a decision by ~361 calls (modulo some captures).

I can add a limit, but it would be nice to capture the board state that led to this, because I feel like it must be a bug in my thinking or my code.

**Comment by oriskunk** [comment]
def is_ladder_capture(self, action, prey=None):
    #...
    call tmp.is_ladder_escapre()

def is_ladder_escape(self, action, prey=None):
    #...
    call tmp.is_ladder_capture()

Could it be in a deadlock?

A. is_ladder_capture()
B. is_ladder_escape()

A->B->A->B->A->B->A->B->A->B->A->B->A->B->A->B

**Comment by thouis** [comment]
Exactly, that looks like what is happening.  But each "->" should add another stone to the board.

**Comment by oriskunk** [comment]
using sys.setrecursionlimit(100000)

Same error...  : (

**Comment by oriskunk** [comment]
![image](https://cloud.githubusercontent.com/assets/22738490/20340504/1a4ca346-ac25-11e6-947f-927720f2239a.png)

x marking is a problem. : )

**Comment by oriskunk** [comment]
other state.
![image](https://cloud.githubusercontent.com/assets/22738490/20340973/826f1150-ac27-11e6-9175-56904d82d8fb.png)

I think it seems to be a problem related to ko. double ko. two-step kos.

**Comment by thouis** [comment]
OK, it looks like all the kos attached to ladder groups is a problem.   I'll add a maximum depth of ~30 to the ladder features.

**Comment by oriskunk** [comment]
thx. : )
and this is my sample code.

def is_ladder_capture(self, action, prey=None, depth=0):    #add depth argument
    if depth > 100:
        return False

    call is_ladder_escape(....., depth=depth+1)

is_ladder_escape() is same.
