### ISSUE TITLE
Something wrong with the installation

### ISSUE THREAD

**Issue by WeakDog** [Rochester-NRT/RocAlphaGo#215]
**I have installed the RocAlphaGo following the Wiki**
**But when I run the test files like** 

   python -m tests.test_supervised_policy_trainer

**there are some errors like this** 

  Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/say/Downloads/RocAlphaGo-develop/tests/test_policy.py", line 1, in <module>
    from AlphaGo.models.policy import CNNPolicy, ResnetPolicy
  File "AlphaGo/models/policy.py", line 1, in <module>
    from keras.models import Sequential, Model
  File "/home/say/.local/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/say/.local/lib/python2.7/site-packages/keras/backend/__init__.py", line 37, in <module>
    assert _backend in {'theano', 'tensorflow'}
AssertionError
 
**So is there anything wrong?**

**Comment by wrongu** [comment]
That looks like an error with your keras installation. Did you already have keras installed? Are you using a virtual environment for your packages? If so, try the following: move or remove your `~/.keras/keras.json` config file, or make sure it has `"backend"` set to either `"theano"` or `"tensorflow"`

**Comment by WeakDog** [comment]
**Yes, it worked after setting "backend" to "tensorflow"
But there is new error like this** 

Esgfs_to_hdf5 failed
E............
======================================================================
ERROR: test_directory_conversion (tests.test_game_converter.TestCmdlineConverter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/say/Downloads/RocAlphaGo-develop/tests/test_game_converter.py", line 19, in test_directory_conversion
    run_game_converter(args)
  File "/home/say/Downloads/RocAlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 225, in run_game_converter
    converter.sgfs_to_hdf5(files, args.outfile, bd_size=args.size, verbose=args.verbose)
  File "/home/say/Downloads/RocAlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 144, in sgfs_to_hdf5
    raise e
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.


**Does it mean I need to install the HDF5?  But I have installed it.**
