### ISSUE TITLE
How to create *model.json for value?

### ISSUE THREAD

**Issue by zongshuai818** [Rochester-NRT/RocAlphaGo#219]
* When i train the network ( reinforcement_policy_trainer,reinforcement_value_trainer,and supervised_policy_trainer ),I used the prepared my_model.json in advance.
* But only the reinforcement_value_trainer didn't work.
  * Error : "Unable to open object (Object 'states' doesn't exist)"
* I guess this reason is: I need a model for the value network.
* So,how to generate the model as *.json by myself ?(for policy ,for value),what command should I execute?

Thank you for answering my question!

**Comment by MaMiFreak** [comment]
It is possible to train a value net but there are some "issues" with it.
first you have to generate data by using the [generate_value_training.py](https://github.com/Rochester-NRT/RocAlphaGo/tree/cython-optimization/AlphaGo/preprocessing) it requires a trained policy net and lets it play games vs itself ( or vs a reinforcement trained policy net)
unfortunately this is pretty slow.. (i managed to generate 4M samples in 2weeks...)

@oriskunk used data released by another team creating a bot and managed to train a value net with that data.

[in this folder](https://github.com/Rochester-NRT/RocAlphaGo/tree/cython-optimization/AlphaGo/models) you can find all the available models and a model.json file is created the same way as for the policy net:
`from AlphaGo.models.value import CNNValue
arch = {'filters_per_layer': 128, 'layers': 12} # args to CNNValue.create_network()
features = ['board', 'ones', 'turns_since'] # Important! This must match args to game_converter
policy = CNNValue(features, **arch)
policy.save_model('my_model.json')`

please be aware that the the last 'zeros' feature layer in the policy net is replaced by a 'colour' feature in the value net. keep the amount of filters the same and you can pre-initialize a part of the value net with the trained policy net. 
This brings us to the second 'issue' or more a TODO, there is not yet a convenient way to provide the value trainer with a policy net so it can initialize the value net. you have to do that yourself

and please use the cython-optimization branch, a few more changes have to be made but i think it is the best branch to use right now, especially when generating value net data

**Comment by zongshuai818** [comment]
@MaMiFreak 

Thank you for your answer! i solved my problem and get my models for "value training"," policy-training",even "rollout-training" . cool !

But i meet a new question when i play the game , this question bothered me for several days.
* When i want to use MCTS to play , i write a "run_MCTS.py" as:
```
from AlphaGo.ai import MCTSPlayer

from AlphaGo.models.value import CNNValue
from AlphaGo.models.policy import CNNPolicy
from AlphaGo.models.rollout import CNNRollout

from interface.gtp_wrapper import run_gtp

#value model
MODEL1 = 'my_value_model.json'
WEIGHTS1 = 'weights_value.hdf5'

value = CNNValue.load_model(MODEL1)
value.model.load_weights(WEIGHTS1)

#policy model
MODEL2 = 'my_policy_model.json'
WEIGHTS2 = 'weights_policy.hdf5'

policy = CNNPolicy.load_model(MODEL2)
policy.model.load_weights(WEIGHTS2)

#rollout
MODEL3 = 'my_rollout_model.json'
WEIGHTS3 = 'weights_rollout.hdf5'

rollout = CNNRollout.load_model(MODEL3)
rollout.model.load_weights(WEIGHTS3)

#player
player = MCTSPlayer(value,policy,rollout)

run_gtp(player)
 ```
 those *.json and *.hdf5 are matched.

* then i runing "run_MCTS.py" using gtp and gogui 
```
 gogui-twogtp -black 'python run_MCTS.py' -white 'gogui-display' -size 19 -komi 7.5 -verbose -auto
```
* **error is coming!**
```
============================================
Game 1
============================================
B>> boardsize 19
B<< =
B<< 
B>> clear_board
B<< =
B<< 
W>> boardsize 19
W<< = 
W<< 
W>> clear_board
W<< = 
W<< 
B>> genmove b
Traceback (most recent call last):
  File "run_MCTS.py", line 35, in <module>
    run_gtp(player)
  File "/home/ubnutu-2/Documents/AlphaGo/RocAlphaGo-debug-value/interface/gtp_wrapper.py", line 152, in run_gtp
    engine_reply = gtp_engine.send(cmd)
  File "/home/ubnutu-2/anaconda2/lib/python2.7/site-packages/gtp.py", line 154, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "/home/ubnutu-2/anaconda2/lib/python2.7/site-packages/gtp.py", line 222, in cmd_genmove
    move = self._game.get_move(c)
  File "/home/ubnutu-2/Documents/AlphaGo/RocAlphaGo-debug-value/interface/gtp_wrapper.py", line 114, in get_move
    move = self._player.get_move(self._state)
  File "/home/ubnutu-2/Documents/AlphaGo/RocAlphaGo-debug-value/AlphaGo/ai.py", line 238, in get_move
    move = self.mcts.get_move(state)
  File "/home/ubnutu-2/Documents/AlphaGo/RocAlphaGo-debug-value/AlphaGo/mcts.py", line 202, in get_move
    self._playout(state_copy, self._L)
  File "/home/ubnutu-2/Documents/AlphaGo/RocAlphaGo-debug-value/AlphaGo/mcts.py", line 151, in _playout
    action_probs = self._policy(state)
TypeError: 'CNNPolicy' object is not callable
B>> final_score
W>> final_score
W<< ? unknown command: final_score
W<< 
B>> quit
W>> quit
W<< = 
W<<
```
**gogui-display can't runing and pop up a window " GTP stream was closed "**

and i have to quit .

The problem did not happen when I was running policy player alone . so i suspect that the problem is caused by MCTS integrated three networks(polocy value rollout) , or have any other problems I did not find.

Do you have any advice?

Thanks again !   ^_^

**Comment by MaMiFreak** [comment]
@zongshuai818 good to hear!

unfortunately i can't help you with the MCTS part, when i joined this project i heard some remarks there was an issue with it but i never had a look at it. first i want to get some multithreading going and depending on how that is going to look like i think the MCTS part is going to be rewritten. but i am afraid that will take some time, i the meantime if you find out how to fix it please create a pull request fixing it=)

**Comment by zongshuai818** [comment]
@MaMiFreak ok , no porblem~

I was trying to solve this problem, and for the quick fix, I also left the same question to another author on this [page](https://github.com/Rochester-NRT/RocAlphaGo/pull/147), if the problem solved, I will sort out a file about simple MCTS for pull request to further improve this function.  ＾▽＾

**Comment by RHF2** [comment]
@zongshuai818 
MCTSPlayer need write functions get move probabilities by policy/value network.

```
from AlphaGo.ai import MCTSPlayer
from AlphaGo.models.value import CNNValue
from AlphaGo.models.policy import CNNPolicy
from AlphaGo.models.rollout import CNNRollout
from interface.gtp_wrapper import run_gtp


def policy_network(state):
    move_probs = policy.eval_state(state, state.get_legal_moves())
    return move_probs 


def value_network(state):
    vn_winrate = value.eval_state(state)
    return vn_winrate


def rollout_policy(state):
    move_probs = rollout.eval_state(state, state.get_legal_moves())
    return move_probs


#value model
MODEL1 = 'my_value_model.json'
WEIGHTS1 = 'weights_value.hdf5'

value = CNNValue.load_model(MODEL1)
value.model.load_weights(WEIGHTS1)

#policy model
MODEL2 = 'my_policy_model.json'
WEIGHTS2 = 'weights_policy.hdf5'

policy = CNNPolicy.load_model(MODEL2)
policy.model.load_weights(WEIGHTS2)

#rollout
MODEL3 = 'my_rollout_model.json'
WEIGHTS3 = 'weights_rollout.hdf5'

rollout = CNNRollout.load_model(MODEL3)
rollout.model.load_weights(WEIGHTS3)

#player
player = MCTSPlayer(value_network,policy_network,rollout_policy)

run_gtp(player)
```

**Comment by zongshuai818** [comment]
@RHF2 This was the answer I was looking for . 

I added these functions , return the state.

Thank you very much!
